% MATLAB script to run Spectral GEDAI on CAUEEG.set
addpath('C:\Users\Utilisateur\Documents\MATLAB\eeglab-developp\plugins\GEDAI-master\');
addpath('C:\Users\Utilisateur\Documents\MATLAB\eeglab-developp\plugins\GEDAI-master\auxiliaries\');
addpath('C:\Users\Utilisateur\Documents\MATLAB\eeglab-developp\');
eeglab nogui;

% Load dataset
EEG = pop_loadset('filename', 'CAUEEG.set', 'filepath', 'C:\Users\Utilisateur\Documents\GitHub\gedai\gedai\data\');

% Load Reference Covariance (Leadfield)
refCOV_struct = load('C:\Users\Utilisateur\Documents\GitHub\gedai\gedai\data\fsavLEADFIELD_4_GEDAI.mat');
refCOV = refCOV_struct.leadfield4GEDAI.gram_matrix_avref'; 

% Positional args: GEDAI(EEGin, artifact_threshold_type, epoch_size_in_cycles, lowcut_frequency, ref_matrix_type, parallel, visualize_artifacts, ENOVA_threshold, signal_type)
[EEGclean, EEGartifacts, SENSAI_score, SENSAI_score_per_band, artifact_threshold_per_band, mean_ENOVA, ENOVA_per_epoch, com, ENOVA_per_band] = GEDAI(...
    EEG, ...
    'auto', ...
    12, ...
    0.5, ...
    refCOV, ...
    false, ...
    false, ...
    inf, ...
    'eeg' ...
);

disp('--------------------------------------------------');
disp(['MATLAB Spectral SENSAI: ', num2str(SENSAI_score)]);
disp(['MATLAB Spectral ENOVA: ', num2str(mean_ENOVA)]);
disp('--------------------------------------------------');
exit;
